# Generated by Django 3.0.8 on 2020-07-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='about',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
