# Generated by Django 3.0.8 on 2020-07-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200713_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
